apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internet
  namespace: innkeeper
spec:
  gatewayClassName: istio
  addresses:
    - value: 10.0.52.80
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
